name: flutter_acd_scanner
description: Pugin to wrapp the functionality of the acd scanner service
version: 1.0.0
homepage: https://www.coodoo.de/
repository: https://github.com/coodoo-io/flutter_acd_scanner

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.coodoo.io.acd_scanner
        pluginClass: AcdScannerPlugin

